// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

public interface CallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MonitoringSystem.CallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val3 = 1;</code>
   */
  java.lang.String getVal3();
  /**
   * <code>string val3 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal3Bytes();

  /**
   * <code>string val4 = 2;</code>
   */
  java.lang.String getVal4();
  /**
   * <code>string val4 = 2;</code>
   */
  com.google.protobuf.ByteString
      getVal4Bytes();

  /**
   * <code>string val5 = 3;</code>
   */
  java.lang.String getVal5();
  /**
   * <code>string val5 = 3;</code>
   */
  com.google.protobuf.ByteString
      getVal5Bytes();
}
