// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

/**
 * Protobuf type {@code MonitoringSystem.CallRequest}
 */
public  final class CallRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MonitoringSystem.CallRequest)
    CallRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallRequest.newBuilder() to construct.
  private CallRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallRequest() {
    val3_ = "";
    val4_ = "";
    val5_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            val3_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            val4_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            val5_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MS.MSServiceImpl.internal_static_MonitoringSystem_CallRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MS.MSServiceImpl.internal_static_MonitoringSystem_CallRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MS.CallRequest.class, MS.CallRequest.Builder.class);
  }

  public static final int VAL3_FIELD_NUMBER = 1;
  private volatile java.lang.Object val3_;
  /**
   * <code>string val3 = 1;</code>
   */
  public java.lang.String getVal3() {
    java.lang.Object ref = val3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      val3_ = s;
      return s;
    }
  }
  /**
   * <code>string val3 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVal3Bytes() {
    java.lang.Object ref = val3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      val3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VAL4_FIELD_NUMBER = 2;
  private volatile java.lang.Object val4_;
  /**
   * <code>string val4 = 2;</code>
   */
  public java.lang.String getVal4() {
    java.lang.Object ref = val4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      val4_ = s;
      return s;
    }
  }
  /**
   * <code>string val4 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVal4Bytes() {
    java.lang.Object ref = val4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      val4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VAL5_FIELD_NUMBER = 3;
  private volatile java.lang.Object val5_;
  /**
   * <code>string val5 = 3;</code>
   */
  public java.lang.String getVal5() {
    java.lang.Object ref = val5_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      val5_ = s;
      return s;
    }
  }
  /**
   * <code>string val5 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVal5Bytes() {
    java.lang.Object ref = val5_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      val5_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVal3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, val3_);
    }
    if (!getVal4Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, val4_);
    }
    if (!getVal5Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, val5_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVal3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, val3_);
    }
    if (!getVal4Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, val4_);
    }
    if (!getVal5Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, val5_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MS.CallRequest)) {
      return super.equals(obj);
    }
    MS.CallRequest other = (MS.CallRequest) obj;

    boolean result = true;
    result = result && getVal3()
        .equals(other.getVal3());
    result = result && getVal4()
        .equals(other.getVal4());
    result = result && getVal5()
        .equals(other.getVal5());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VAL3_FIELD_NUMBER;
    hash = (53 * hash) + getVal3().hashCode();
    hash = (37 * hash) + VAL4_FIELD_NUMBER;
    hash = (53 * hash) + getVal4().hashCode();
    hash = (37 * hash) + VAL5_FIELD_NUMBER;
    hash = (53 * hash) + getVal5().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MS.CallRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.CallRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.CallRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.CallRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.CallRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.CallRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.CallRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MS.CallRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MS.CallRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MS.CallRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MS.CallRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MS.CallRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MS.CallRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MonitoringSystem.CallRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MonitoringSystem.CallRequest)
      MS.CallRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_CallRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_CallRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MS.CallRequest.class, MS.CallRequest.Builder.class);
    }

    // Construct using MS.CallRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      val3_ = "";

      val4_ = "";

      val5_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_CallRequest_descriptor;
    }

    @java.lang.Override
    public MS.CallRequest getDefaultInstanceForType() {
      return MS.CallRequest.getDefaultInstance();
    }

    @java.lang.Override
    public MS.CallRequest build() {
      MS.CallRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MS.CallRequest buildPartial() {
      MS.CallRequest result = new MS.CallRequest(this);
      result.val3_ = val3_;
      result.val4_ = val4_;
      result.val5_ = val5_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MS.CallRequest) {
        return mergeFrom((MS.CallRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MS.CallRequest other) {
      if (other == MS.CallRequest.getDefaultInstance()) return this;
      if (!other.getVal3().isEmpty()) {
        val3_ = other.val3_;
        onChanged();
      }
      if (!other.getVal4().isEmpty()) {
        val4_ = other.val4_;
        onChanged();
      }
      if (!other.getVal5().isEmpty()) {
        val5_ = other.val5_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MS.CallRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MS.CallRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object val3_ = "";
    /**
     * <code>string val3 = 1;</code>
     */
    public java.lang.String getVal3() {
      java.lang.Object ref = val3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string val3 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVal3Bytes() {
      java.lang.Object ref = val3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string val3 = 1;</code>
     */
    public Builder setVal3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      val3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string val3 = 1;</code>
     */
    public Builder clearVal3() {
      
      val3_ = getDefaultInstance().getVal3();
      onChanged();
      return this;
    }
    /**
     * <code>string val3 = 1;</code>
     */
    public Builder setVal3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      val3_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object val4_ = "";
    /**
     * <code>string val4 = 2;</code>
     */
    public java.lang.String getVal4() {
      java.lang.Object ref = val4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string val4 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVal4Bytes() {
      java.lang.Object ref = val4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string val4 = 2;</code>
     */
    public Builder setVal4(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      val4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string val4 = 2;</code>
     */
    public Builder clearVal4() {
      
      val4_ = getDefaultInstance().getVal4();
      onChanged();
      return this;
    }
    /**
     * <code>string val4 = 2;</code>
     */
    public Builder setVal4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      val4_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object val5_ = "";
    /**
     * <code>string val5 = 3;</code>
     */
    public java.lang.String getVal5() {
      java.lang.Object ref = val5_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val5_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string val5 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVal5Bytes() {
      java.lang.Object ref = val5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string val5 = 3;</code>
     */
    public Builder setVal5(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      val5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string val5 = 3;</code>
     */
    public Builder clearVal5() {
      
      val5_ = getDefaultInstance().getVal5();
      onChanged();
      return this;
    }
    /**
     * <code>string val5 = 3;</code>
     */
    public Builder setVal5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      val5_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MonitoringSystem.CallRequest)
  }

  // @@protoc_insertion_point(class_scope:MonitoringSystem.CallRequest)
  private static final MS.CallRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MS.CallRequest();
  }

  public static MS.CallRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallRequest>
      PARSER = new com.google.protobuf.AbstractParser<CallRequest>() {
    @java.lang.Override
    public CallRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CallRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MS.CallRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

