// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

public interface CallResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MonitoringSystem.CallResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val6 = 1;</code>
   */
  java.lang.String getVal6();
  /**
   * <code>string val6 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal6Bytes();

  /**
   * <code>string val7 = 2;</code>
   */
  java.lang.String getVal7();
  /**
   * <code>string val7 = 2;</code>
   */
  com.google.protobuf.ByteString
      getVal7Bytes();

  /**
   * <code>string val8 = 3;</code>
   */
  java.lang.String getVal8();
  /**
   * <code>string val8 = 3;</code>
   */
  com.google.protobuf.ByteString
      getVal8Bytes();
}
