// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

/**
 * Protobuf type {@code MonitoringSystem.CallResponse}
 */
public  final class CallResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MonitoringSystem.CallResponse)
    CallResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallResponse.newBuilder() to construct.
  private CallResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallResponse() {
    val6_ = "";
    val7_ = "";
    val8_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            val6_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            val7_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            val8_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MS.MSServiceImpl.internal_static_MonitoringSystem_CallResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MS.MSServiceImpl.internal_static_MonitoringSystem_CallResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MS.CallResponse.class, MS.CallResponse.Builder.class);
  }

  public static final int VAL6_FIELD_NUMBER = 1;
  private volatile java.lang.Object val6_;
  /**
   * <code>string val6 = 1;</code>
   */
  public java.lang.String getVal6() {
    java.lang.Object ref = val6_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      val6_ = s;
      return s;
    }
  }
  /**
   * <code>string val6 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVal6Bytes() {
    java.lang.Object ref = val6_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      val6_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VAL7_FIELD_NUMBER = 2;
  private volatile java.lang.Object val7_;
  /**
   * <code>string val7 = 2;</code>
   */
  public java.lang.String getVal7() {
    java.lang.Object ref = val7_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      val7_ = s;
      return s;
    }
  }
  /**
   * <code>string val7 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVal7Bytes() {
    java.lang.Object ref = val7_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      val7_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VAL8_FIELD_NUMBER = 3;
  private volatile java.lang.Object val8_;
  /**
   * <code>string val8 = 3;</code>
   */
  public java.lang.String getVal8() {
    java.lang.Object ref = val8_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      val8_ = s;
      return s;
    }
  }
  /**
   * <code>string val8 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVal8Bytes() {
    java.lang.Object ref = val8_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      val8_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVal6Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, val6_);
    }
    if (!getVal7Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, val7_);
    }
    if (!getVal8Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, val8_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVal6Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, val6_);
    }
    if (!getVal7Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, val7_);
    }
    if (!getVal8Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, val8_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MS.CallResponse)) {
      return super.equals(obj);
    }
    MS.CallResponse other = (MS.CallResponse) obj;

    boolean result = true;
    result = result && getVal6()
        .equals(other.getVal6());
    result = result && getVal7()
        .equals(other.getVal7());
    result = result && getVal8()
        .equals(other.getVal8());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VAL6_FIELD_NUMBER;
    hash = (53 * hash) + getVal6().hashCode();
    hash = (37 * hash) + VAL7_FIELD_NUMBER;
    hash = (53 * hash) + getVal7().hashCode();
    hash = (37 * hash) + VAL8_FIELD_NUMBER;
    hash = (53 * hash) + getVal8().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MS.CallResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.CallResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.CallResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.CallResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.CallResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.CallResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.CallResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MS.CallResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MS.CallResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MS.CallResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MS.CallResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MS.CallResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MS.CallResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MonitoringSystem.CallResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MonitoringSystem.CallResponse)
      MS.CallResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_CallResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_CallResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MS.CallResponse.class, MS.CallResponse.Builder.class);
    }

    // Construct using MS.CallResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      val6_ = "";

      val7_ = "";

      val8_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_CallResponse_descriptor;
    }

    @java.lang.Override
    public MS.CallResponse getDefaultInstanceForType() {
      return MS.CallResponse.getDefaultInstance();
    }

    @java.lang.Override
    public MS.CallResponse build() {
      MS.CallResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MS.CallResponse buildPartial() {
      MS.CallResponse result = new MS.CallResponse(this);
      result.val6_ = val6_;
      result.val7_ = val7_;
      result.val8_ = val8_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MS.CallResponse) {
        return mergeFrom((MS.CallResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MS.CallResponse other) {
      if (other == MS.CallResponse.getDefaultInstance()) return this;
      if (!other.getVal6().isEmpty()) {
        val6_ = other.val6_;
        onChanged();
      }
      if (!other.getVal7().isEmpty()) {
        val7_ = other.val7_;
        onChanged();
      }
      if (!other.getVal8().isEmpty()) {
        val8_ = other.val8_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MS.CallResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MS.CallResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object val6_ = "";
    /**
     * <code>string val6 = 1;</code>
     */
    public java.lang.String getVal6() {
      java.lang.Object ref = val6_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val6_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string val6 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVal6Bytes() {
      java.lang.Object ref = val6_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string val6 = 1;</code>
     */
    public Builder setVal6(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      val6_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string val6 = 1;</code>
     */
    public Builder clearVal6() {
      
      val6_ = getDefaultInstance().getVal6();
      onChanged();
      return this;
    }
    /**
     * <code>string val6 = 1;</code>
     */
    public Builder setVal6Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      val6_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object val7_ = "";
    /**
     * <code>string val7 = 2;</code>
     */
    public java.lang.String getVal7() {
      java.lang.Object ref = val7_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val7_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string val7 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVal7Bytes() {
      java.lang.Object ref = val7_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val7_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string val7 = 2;</code>
     */
    public Builder setVal7(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      val7_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string val7 = 2;</code>
     */
    public Builder clearVal7() {
      
      val7_ = getDefaultInstance().getVal7();
      onChanged();
      return this;
    }
    /**
     * <code>string val7 = 2;</code>
     */
    public Builder setVal7Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      val7_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object val8_ = "";
    /**
     * <code>string val8 = 3;</code>
     */
    public java.lang.String getVal8() {
      java.lang.Object ref = val8_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val8_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string val8 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVal8Bytes() {
      java.lang.Object ref = val8_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val8_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string val8 = 3;</code>
     */
    public Builder setVal8(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      val8_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string val8 = 3;</code>
     */
    public Builder clearVal8() {
      
      val8_ = getDefaultInstance().getVal8();
      onChanged();
      return this;
    }
    /**
     * <code>string val8 = 3;</code>
     */
    public Builder setVal8Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      val8_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MonitoringSystem.CallResponse)
  }

  // @@protoc_insertion_point(class_scope:MonitoringSystem.CallResponse)
  private static final MS.CallResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MS.CallResponse();
  }

  public static MS.CallResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallResponse>
      PARSER = new com.google.protobuf.AbstractParser<CallResponse>() {
    @java.lang.Override
    public CallResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CallResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MS.CallResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

