// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

public interface LiveDashboardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MonitoringSystem.LiveDashboardResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val2 = 1;</code>
   */
  java.lang.String getVal2();
  /**
   * <code>string val2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal2Bytes();

  /**
   * <code>int32 temp2 = 2;</code>
   */
  int getTemp2();

  /**
   * <code>string occupant2 = 3;</code>
   */
  java.lang.String getOccupant2();
  /**
   * <code>string occupant2 = 3;</code>
   */
  com.google.protobuf.ByteString
      getOccupant2Bytes();
}
