// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

public interface LiveDashboardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MonitoringSystem.LiveDashboardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val1 = 1;</code>
   */
  java.lang.String getVal1();
  /**
   * <code>string val1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal1Bytes();

  /**
   * <code>int32 temp1 = 2;</code>
   */
  int getTemp1();

  /**
   * <code>string occupant1 = 3;</code>
   */
  java.lang.String getOccupant1();
  /**
   * <code>string occupant1 = 3;</code>
   */
  com.google.protobuf.ByteString
      getOccupant1Bytes();
}
