// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

/**
 * Protobuf type {@code MonitoringSystem.LiveDashboardRequest}
 */
public  final class LiveDashboardRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MonitoringSystem.LiveDashboardRequest)
    LiveDashboardRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LiveDashboardRequest.newBuilder() to construct.
  private LiveDashboardRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LiveDashboardRequest() {
    val1_ = "";
    temp1_ = 0;
    occupant1_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LiveDashboardRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            val1_ = s;
            break;
          }
          case 16: {

            temp1_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            occupant1_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MS.MSServiceImpl.internal_static_MonitoringSystem_LiveDashboardRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MS.MSServiceImpl.internal_static_MonitoringSystem_LiveDashboardRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MS.LiveDashboardRequest.class, MS.LiveDashboardRequest.Builder.class);
  }

  public static final int VAL1_FIELD_NUMBER = 1;
  private volatile java.lang.Object val1_;
  /**
   * <code>string val1 = 1;</code>
   */
  public java.lang.String getVal1() {
    java.lang.Object ref = val1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      val1_ = s;
      return s;
    }
  }
  /**
   * <code>string val1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVal1Bytes() {
    java.lang.Object ref = val1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      val1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEMP1_FIELD_NUMBER = 2;
  private int temp1_;
  /**
   * <code>int32 temp1 = 2;</code>
   */
  public int getTemp1() {
    return temp1_;
  }

  public static final int OCCUPANT1_FIELD_NUMBER = 3;
  private volatile java.lang.Object occupant1_;
  /**
   * <code>string occupant1 = 3;</code>
   */
  public java.lang.String getOccupant1() {
    java.lang.Object ref = occupant1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      occupant1_ = s;
      return s;
    }
  }
  /**
   * <code>string occupant1 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOccupant1Bytes() {
    java.lang.Object ref = occupant1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      occupant1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVal1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, val1_);
    }
    if (temp1_ != 0) {
      output.writeInt32(2, temp1_);
    }
    if (!getOccupant1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, occupant1_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVal1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, val1_);
    }
    if (temp1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, temp1_);
    }
    if (!getOccupant1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, occupant1_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MS.LiveDashboardRequest)) {
      return super.equals(obj);
    }
    MS.LiveDashboardRequest other = (MS.LiveDashboardRequest) obj;

    boolean result = true;
    result = result && getVal1()
        .equals(other.getVal1());
    result = result && (getTemp1()
        == other.getTemp1());
    result = result && getOccupant1()
        .equals(other.getOccupant1());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VAL1_FIELD_NUMBER;
    hash = (53 * hash) + getVal1().hashCode();
    hash = (37 * hash) + TEMP1_FIELD_NUMBER;
    hash = (53 * hash) + getTemp1();
    hash = (37 * hash) + OCCUPANT1_FIELD_NUMBER;
    hash = (53 * hash) + getOccupant1().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MS.LiveDashboardRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.LiveDashboardRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.LiveDashboardRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.LiveDashboardRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.LiveDashboardRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MS.LiveDashboardRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MS.LiveDashboardRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MS.LiveDashboardRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MS.LiveDashboardRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MS.LiveDashboardRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MS.LiveDashboardRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MS.LiveDashboardRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MS.LiveDashboardRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MonitoringSystem.LiveDashboardRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MonitoringSystem.LiveDashboardRequest)
      MS.LiveDashboardRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_LiveDashboardRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_LiveDashboardRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MS.LiveDashboardRequest.class, MS.LiveDashboardRequest.Builder.class);
    }

    // Construct using MS.LiveDashboardRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      val1_ = "";

      temp1_ = 0;

      occupant1_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MS.MSServiceImpl.internal_static_MonitoringSystem_LiveDashboardRequest_descriptor;
    }

    @java.lang.Override
    public MS.LiveDashboardRequest getDefaultInstanceForType() {
      return MS.LiveDashboardRequest.getDefaultInstance();
    }

    @java.lang.Override
    public MS.LiveDashboardRequest build() {
      MS.LiveDashboardRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MS.LiveDashboardRequest buildPartial() {
      MS.LiveDashboardRequest result = new MS.LiveDashboardRequest(this);
      result.val1_ = val1_;
      result.temp1_ = temp1_;
      result.occupant1_ = occupant1_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MS.LiveDashboardRequest) {
        return mergeFrom((MS.LiveDashboardRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MS.LiveDashboardRequest other) {
      if (other == MS.LiveDashboardRequest.getDefaultInstance()) return this;
      if (!other.getVal1().isEmpty()) {
        val1_ = other.val1_;
        onChanged();
      }
      if (other.getTemp1() != 0) {
        setTemp1(other.getTemp1());
      }
      if (!other.getOccupant1().isEmpty()) {
        occupant1_ = other.occupant1_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MS.LiveDashboardRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MS.LiveDashboardRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object val1_ = "";
    /**
     * <code>string val1 = 1;</code>
     */
    public java.lang.String getVal1() {
      java.lang.Object ref = val1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string val1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVal1Bytes() {
      java.lang.Object ref = val1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string val1 = 1;</code>
     */
    public Builder setVal1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      val1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string val1 = 1;</code>
     */
    public Builder clearVal1() {
      
      val1_ = getDefaultInstance().getVal1();
      onChanged();
      return this;
    }
    /**
     * <code>string val1 = 1;</code>
     */
    public Builder setVal1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      val1_ = value;
      onChanged();
      return this;
    }

    private int temp1_ ;
    /**
     * <code>int32 temp1 = 2;</code>
     */
    public int getTemp1() {
      return temp1_;
    }
    /**
     * <code>int32 temp1 = 2;</code>
     */
    public Builder setTemp1(int value) {
      
      temp1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 temp1 = 2;</code>
     */
    public Builder clearTemp1() {
      
      temp1_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object occupant1_ = "";
    /**
     * <code>string occupant1 = 3;</code>
     */
    public java.lang.String getOccupant1() {
      java.lang.Object ref = occupant1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        occupant1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string occupant1 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOccupant1Bytes() {
      java.lang.Object ref = occupant1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        occupant1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string occupant1 = 3;</code>
     */
    public Builder setOccupant1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      occupant1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string occupant1 = 3;</code>
     */
    public Builder clearOccupant1() {
      
      occupant1_ = getDefaultInstance().getOccupant1();
      onChanged();
      return this;
    }
    /**
     * <code>string occupant1 = 3;</code>
     */
    public Builder setOccupant1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      occupant1_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MonitoringSystem.LiveDashboardRequest)
  }

  // @@protoc_insertion_point(class_scope:MonitoringSystem.LiveDashboardRequest)
  private static final MS.LiveDashboardRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MS.LiveDashboardRequest();
  }

  public static MS.LiveDashboardRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LiveDashboardRequest>
      PARSER = new com.google.protobuf.AbstractParser<LiveDashboardRequest>() {
    @java.lang.Override
    public LiveDashboardRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LiveDashboardRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LiveDashboardRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LiveDashboardRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MS.LiveDashboardRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

