// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MS.proto

package MS;

public final class MSServiceImpl {
  private MSServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitoringSystem_LiveDashboardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitoringSystem_LiveDashboardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitoringSystem_LiveDashboardResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitoringSystem_LiveDashboardResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitoringSystem_CallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitoringSystem_CallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitoringSystem_CallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitoringSystem_CallResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010MS.proto\022\020MonitoringSystem\"F\n\024LiveDash" +
      "boardRequest\022\014\n\004val1\030\001 \001(\t\022\r\n\005temp1\030\002 \001(" +
      "\005\022\021\n\toccupant1\030\003 \001(\t\"G\n\025LiveDashboardRes" +
      "ponse\022\014\n\004val2\030\001 \001(\t\022\r\n\005temp2\030\002 \001(\005\022\021\n\toc" +
      "cupant2\030\003 \001(\t\"7\n\013CallRequest\022\014\n\004val3\030\001 \001" +
      "(\t\022\014\n\004val4\030\002 \001(\t\022\014\n\004val5\030\003 \001(\t\"8\n\014CallRe" +
      "sponse\022\014\n\004val6\030\001 \001(\t\022\014\n\004val7\030\002 \001(\t\022\014\n\004va" +
      "l8\030\003 \001(\t2\320\001\n\020MonitoringSystem\022f\n\rLiveDas" +
      "hboard\022&.MonitoringSystem.LiveDashboardR" +
      "equest\032\'.MonitoringSystem.LiveDashboardR" +
      "esponse\"\000(\0010\001\022T\n\021EmergencyServices\022\035.Mon" +
      "itoringSystem.CallRequest\032\036.MonitoringSy" +
      "stem.CallResponse0\001B\025\n\002MSB\rMSServiceImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MonitoringSystem_LiveDashboardRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MonitoringSystem_LiveDashboardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitoringSystem_LiveDashboardRequest_descriptor,
        new java.lang.String[] { "Val1", "Temp1", "Occupant1", });
    internal_static_MonitoringSystem_LiveDashboardResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MonitoringSystem_LiveDashboardResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitoringSystem_LiveDashboardResponse_descriptor,
        new java.lang.String[] { "Val2", "Temp2", "Occupant2", });
    internal_static_MonitoringSystem_CallRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MonitoringSystem_CallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitoringSystem_CallRequest_descriptor,
        new java.lang.String[] { "Val3", "Val4", "Val5", });
    internal_static_MonitoringSystem_CallResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MonitoringSystem_CallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitoringSystem_CallResponse_descriptor,
        new java.lang.String[] { "Val6", "Val7", "Val8", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
