// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package Authorization;

public final class AServiceImpl {
  private AServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Access_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Access_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Access_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Access_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Access_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Access_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Access_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Access_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Access_FloorUnitSelectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Access_FloorUnitSelectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Access_FloorUnitSelectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Access_FloorUnitSelectionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\022\006Access\"\034\n\014LoginRequest\022\014\n" +
      "\004val1\030\001 \001(\t\"\035\n\rLoginResponse\022\014\n\004val2\030\001 \001" +
      "(\t\"W\n\007Message\022$\n\006detail\030\001 \001(\0162\024.Access.M" +
      "essage.Enum\"&\n\004Enum\022\013\n\007UNKNOWN\020\000\022\007\n\003LOW\020" +
      "\001\022\010\n\004HIGH\020\002\"\007\n\005Empty\")\n\031FloorUnitSelecti" +
      "onRequest\022\014\n\004val3\030\001 \001(\t\"*\n\032FloorUnitSele" +
      "ctionResponse\022\014\n\004val4\030\001 \001(\t2\321\001\n\rAuthoriz" +
      "ation\0226\n\005Login\022\024.Access.LoginRequest\032\025.A" +
      "ccess.LoginResponse\"\000\022)\n\005empty\022\017.Access." +
      "Message\032\r.Access.Empty\"\000\022]\n\022FloorUnitSel" +
      "ection\022!.Access.FloorUnitSelectionReques" +
      "t\032\".Access.FloorUnitSelectionResponse\"\000B" +
      "\037\n\rAuthorizationB\014AServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Access_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Access_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Access_LoginRequest_descriptor,
        new java.lang.String[] { "Val1", });
    internal_static_Access_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Access_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Access_LoginResponse_descriptor,
        new java.lang.String[] { "Val2", });
    internal_static_Access_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Access_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Access_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_Access_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Access_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Access_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Access_FloorUnitSelectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Access_FloorUnitSelectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Access_FloorUnitSelectionRequest_descriptor,
        new java.lang.String[] { "Val3", });
    internal_static_Access_FloorUnitSelectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Access_FloorUnitSelectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Access_FloorUnitSelectionResponse_descriptor,
        new java.lang.String[] { "Val4", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
