// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package Authorization;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Access.Empty)
    com.google.protobuf.MessageOrBuilder {
}
