// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package Authorization;

public interface FloorUnitSelectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Access.FloorUnitSelectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val3 = 1;</code>
   */
  java.lang.String getVal3();
  /**
   * <code>string val3 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal3Bytes();
}
