// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package Authorization;

public interface FloorUnitSelectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Access.FloorUnitSelectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val4 = 1;</code>
   */
  java.lang.String getVal4();
  /**
   * <code>string val4 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal4Bytes();
}
