// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package Authorization;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Access.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val2 = 1;</code>
   */
  java.lang.String getVal2();
  /**
   * <code>string val2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal2Bytes();
}
