// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package Authorization;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Access.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Access.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.Access.Message.Enum detail = 1;</code>
   */
  Authorization.Message.Enum getDetail();
}
