// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MTS.proto

package MTS;

public interface LightActivationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MotionTemperatureSensor.LightActivationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val1 = 1;</code>
   */
  java.lang.String getVal1();
  /**
   * <code>string val1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal1Bytes();
}
