// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MTS.proto

package MTS;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MotionTemperatureSensor.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MotionTemperatureSensor.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.MotionTemperatureSensor.Message.Enum detail = 1;</code>
   */
  MTS.Message.Enum getDetail();
}
