// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MTS.proto

package MTS;

public final class MTSServiceImpl {
  private MTSServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MotionTemperatureSensor_LightActivationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MotionTemperatureSensor_LightActivationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MotionTemperatureSensor_LightActivationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MotionTemperatureSensor_LightActivationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MotionTemperatureSensor_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MotionTemperatureSensor_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MotionTemperatureSensor_TempRegulatorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MotionTemperatureSensor_TempRegulatorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MotionTemperatureSensor_TempRegulatorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MotionTemperatureSensor_TempRegulatorRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMTS.proto\022\027MotionTemperatureSensor\"&\n\026" +
      "LightActivationRequest\022\014\n\004val1\030\001 \001(\t\"\'\n\027" +
      "LightActivationResponse\022\014\n\004val2\030\001 \001(\t\"h\n" +
      "\007Message\0225\n\006detail\030\001 \001(\0162%.MotionTempera" +
      "tureSensor.Message.Enum\"&\n\004Enum\022\013\n\007UNKNO" +
      "WN\020\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"(\n\025TempRegulator" +
      "Response\022\017\n\007celcius\030\001 \001(\005\"#\n\024TempRegulat" +
      "orRequest\022\013\n\003val\030\001 \001(\t2\203\002\n\027MotionTempera" +
      "tureSensor\022v\n\017LightActivation\022/.MotionTe" +
      "mperatureSensor.LightActivationRequest\0320" +
      ".MotionTemperatureSensor.LightActivation" +
      "Response\"\000\022p\n\rTempRegulator\022-.MotionTemp" +
      "eratureSensor.TempRegulatorRequest\032..Mot" +
      "ionTemperatureSensor.TempRegulatorRespon" +
      "se(\001B\027\n\003MTSB\016MTSServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MotionTemperatureSensor_LightActivationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MotionTemperatureSensor_LightActivationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MotionTemperatureSensor_LightActivationRequest_descriptor,
        new java.lang.String[] { "Val1", });
    internal_static_MotionTemperatureSensor_LightActivationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MotionTemperatureSensor_LightActivationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MotionTemperatureSensor_LightActivationResponse_descriptor,
        new java.lang.String[] { "Val2", });
    internal_static_MotionTemperatureSensor_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MotionTemperatureSensor_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MotionTemperatureSensor_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_MotionTemperatureSensor_TempRegulatorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MotionTemperatureSensor_TempRegulatorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MotionTemperatureSensor_TempRegulatorResponse_descriptor,
        new java.lang.String[] { "Celcius", });
    internal_static_MotionTemperatureSensor_TempRegulatorRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MotionTemperatureSensor_TempRegulatorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MotionTemperatureSensor_TempRegulatorRequest_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
