// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MTS.proto

package MTS;

public interface TempRegulatorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MotionTemperatureSensor.TempRegulatorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 celcius = 1;</code>
   */
  int getCelcius();
}
